// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAabHEwbSlR-z_Si_Kijv-7ena9DR2kqA',
    appId: '1:1074657419220:web:da806cfddd28c7fad44041',
    messagingSenderId: '1074657419220',
    projectId: 'eartip-f150c',
    authDomain: 'eartip-f150c.firebaseapp.com',
    storageBucket: 'eartip-f150c.firebasestorage.app',
    measurementId: 'G-BBY2P1Y1RL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTHGh6c9C16kji9xJ-OmgjIdPqIWf8AmY',
    appId: '1:1074657419220:android:f8128e5099cf3809d44041',
    messagingSenderId: '1074657419220',
    projectId: 'eartip-f150c',
    storageBucket: 'eartip-f150c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIaY6NR4kSOZnvBzaa4eWQYvBPnzhyME',
    appId: '1:1074657419220:ios:c65671f9f11f976fd44041',
    messagingSenderId: '1074657419220',
    projectId: 'eartip-f150c',
    storageBucket: 'eartip-f150c.firebasestorage.app',
    iosBundleId: 'com.example.eartips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoIaY6NR4kSOZnvBzaa4eWQYvBPnzhyME',
    appId: '1:1074657419220:ios:c65671f9f11f976fd44041',
    messagingSenderId: '1074657419220',
    projectId: 'eartip-f150c',
    storageBucket: 'eartip-f150c.firebasestorage.app',
    iosBundleId: 'com.example.eartips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAabHEwbSlR-z_Si_Kijv-7ena9DR2kqA',
    appId: '1:1074657419220:web:93f0f0461cd6668ad44041',
    messagingSenderId: '1074657419220',
    projectId: 'eartip-f150c',
    authDomain: 'eartip-f150c.firebaseapp.com',
    storageBucket: 'eartip-f150c.firebasestorage.app',
    measurementId: 'G-1VGLGSWMMR',
  );
}
